export const poolInfo = [
  {
    id: 13234,
    stake_token: 'BNB-SLP',
    reward_token: 'SLP',
    start_date: '09/05/22',
    end_date: '01/05/24',
    reward_rate: '300',
    type: 'aquarium',
    status: 'active',
  },

  {
    id: 948894,
    stake_token: 'BNB-CFC',
    reward_token: 'CFC',
    start_date: '09/05/22',
    end_date: '01/05/24',
    reward_rate: '130',
    type: 'uranium',
    status: 'active',
  },

  {
    id: 98300,
    stake_token: 'BNB-NAT',
    reward_token: 'NAT',
    start_date: '09/15/23',
    end_date: '01/05/24',
    reward_rate: '220',
    type: 'uranium',
    status: 'active',
  },
  {
    id: 984024,
    stake_token: 'MATIC-YTC',
    reward_token: 'YTC',
    start_date: '04/31/22',
    end_date: '09/22/23',
    reward_rate: '170',
    type: 'aquarium',
    status: 'active',
  },
  {
    id: 39750,
    stake_token: 'BNB-KCC',
    reward_token: 'KCC',
    start_date: '10/30/22',
    end_date: '01/25/24',
    reward_rate: '300',
    type: 'aquarium',
    status: 'active',
  },
];
