export const poolInfo = [
  {
    id: 13234,
    stake_token: 'BNB-SLP',
    reward_token: 'SLP',
    start_date: '09/05/22',
    end_date: '01/05/24',
    reward_rate: '300',
    type: 'aquarium',
    status: 'active',
  },
  {
    id: 17734,
    stake_token: 'USDT-SLP',
    reward_token: 'SLP',
    start_date: '04/09/22',
    end_date: '11/05/24',
    reward_rate: '120',
    type: 'aquarium',
    status: 'active',
  },
  {
    id: 67234,
    stake_token: 'BNB-CMCC',
    reward_token: 'CMCC',
    start_date: '11/09/23',
    end_date: '01/03/25',
    reward_rate: '70',
    type: 'uranium',
    status: 'active',
  },
  {
    id: 19014,
    stake_token: 'APE NFT',
    reward_token: 'APE',
    start_date: '12/23/22',
    end_date: '11/15/23',
    reward_rate: 'N/A',
    type: 'paladium',
    status: 'active',
  },
  {
    id: 19834,
    stake_token: 'USDC-NGN',
    reward_token: 'NGN',
    start_date: '09/05/22',
    end_date: '01/20/23',
    reward_rate: '320',
    type: 'aquarium',
    status: 'active',
  },
  {
    id: 136711,
    stake_token: 'ETH-EQX',
    reward_token: 'EQX',
    start_date: '05/30/23',
    end_date: '11/19/24',
    reward_rate: '190',
    type: 'uranium',
    status: 'active',
  },
  {
    id: 14546,
    stake_token: 'TRX-UGC',
    reward_token: 'UGC',
    start_date: '12/05/22',
    end_date: '11/22/24',
    reward_rate: '340',
    type: 'aquarium',
    status: 'active',
  },
  {
    id: 10234,
    stake_token: 'ONE-GQC',
    reward_token: 'GQC',
    start_date: '01/05/22',
    end_date: '09/12/22',
    reward_rate: '270',
    type: 'uranium',
    status: 'ended',
  },
  {
    id: 19334,
    stake_token: 'MATIC-CYC',
    reward_token: 'CYC',
    start_date: '02/15/23',
    end_date: '11/05/24',
    reward_rate: '450',
    type: 'aquarium',
    status: 'active',
  },
  {
    id: 130184,
    stake_token: 'BTC_OGC',
    reward_token: 'OGC',
    start_date: '03/23/22',
    end_date: '01/11/24',
    reward_rate: '360',
    type: 'uranium',
    status: 'active',
  },
  {
    id: 13984,
    stake_token: 'ETH-OFN',
    reward_token: 'OFN',
    start_date: '11/25/22',
    end_date: '05/15/24',
    reward_rate: '140',
    type: 'uranium',
    status: 'active',
  },
  {
    id: 13534,
    stake_token: 'DOODLE',
    reward_token: 'PAR',
    start_date: '05/25/22',
    end_date: '01/05/23',
    reward_rate: 'N/A',
    type: 'paladium',
    status: 'active',
  },

  {
    id: 13744,
    stake_token: 'IYOLA NFT',
    reward_token: 'MATIC',
    start_date: '01/19/22',
    end_date: '05/19/22',
    reward_rate: 'N/A',
    type: 'paladium',
    status: 'ended',
  },
  {
    id: 234398,
    stake_token: 'BNB-CSC',
    reward_token: 'CSC',
    start_date: '09/13/22',
    end_date: '05/31/23',
    reward_rate: '120',
    type: 'aquarium',
    status: 'active',
  },
  {
    id: 74922,
    stake_token: 'ADA-MGC',
    reward_token: 'MGC',
    start_date: '02/02/23',
    end_date: '11/15/24',
    reward_rate: '150',
    type: 'uranium',
    status: 'active',
  },
  {
    id: 583920,
    stake_token: 'MATIC-FTT',
    reward_token: 'FTT',
    start_date: '08/22/23',
    end_date: '05/21/24',
    reward_rate: '192',
    type: 'aquarium',
    status: 'active',
  },
  {
    id: 948894,
    stake_token: 'BNB-CFC',
    reward_token: 'CFC',
    start_date: '09/05/22',
    end_date: '01/05/24',
    reward_rate: '130',
    type: 'uranium',
    status: 'active',
  },

  {
    id: 98300,
    stake_token: 'BNB-NAT',
    reward_token: 'NAT',
    start_date: '09/15/23',
    end_date: '01/05/24',
    reward_rate: '220',
    type: 'uranium',
    status: 'active',
  },
  {
    id: 984024,
    stake_token: 'MATIC-YTC',
    reward_token: 'YTC',
    start_date: '04/31/22',
    end_date: '09/22/23',
    reward_rate: '170',
    type: 'aquarium',
    status: 'active',
  },
  {
    id: 39750,
    stake_token: 'BNB-KCC',
    reward_token: 'KCC',
    start_date: '10/30/22',
    end_date: '01/25/24',
    reward_rate: '300',
    type: 'aquarium',
    status: 'active',
  },
  {
    id: 74837,
    stake_token: 'ETH-PPC',
    reward_token: 'PPC',
    start_date: '06/15/22',
    end_date: '11/25/24',
    reward_rate: '280',
    type: 'uranium',
    status: 'active',
  },
  {
    id: 39850,
    stake_token: 'BING NFT',
    reward_token: 'USDC',
    start_date: '12/09/22',
    end_date: '12/05/24',
    reward_rate: 'N/A',
    type: 'paladium',
    status: 'active',
  },
  {
    id: 39378,
    stake_token: 'VISNEY NFT',
    reward_token: 'VIZ',
    start_date: '11/20/22',
    end_date: '03/15/23',
    reward_rate: 'N/A',
    type: 'paladium',
    status: 'active',
  },
];
